TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.18          #基座允许的最大线速度，单位meters/sec (double, default: 0.5)
  min_vel_x: 0.08          #基座允许的最小线速度，单位meters/sec (double, default: 0.1)

  max_vel_theta:  1.0      #基座允许的最大角速度，单位 radians/sec (double, default: 1.0)
  min_vel_theta: -1.0      #基座允许的最小角速度，单位 radians/sec (double, default: -1.0)
  min_in_place_vel_theta: 1.0 #原地旋转时，基座允许的最小角速度，单位 radians/sec
                              #(double, default: 0.4)
  acc_lim_x: 1.0           #机器人在x方向的最大加速度，单位meters/sec^2 (double, default: 2.5)
  acc_lim_y: 1.0           #机器人在y方向的最大加速度，单位meters/sec^2 (double, default: 2.5)
  acc_lim_theta: 1.0       #机器人的最大角加速度，单位radians/sec^2 (double, default: 3.2)

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.02  #到达目标时x&y方向允许的误差 (double, default: 0.10)
  yaw_goal_tolerance: 0.05 #到达目标时角度允许的误差 (double, default: 0.05)

# Differential-drive robot configuration
  holonomic_robot: false   #确定是否为全向轮或非全向轮机器人生成速度指令 (bool, default: true)

# Forward Simulation Parameters
  sim_time: 0.8            #前向模拟轨迹的时间，单位为 seconds (double, default: 1.0)
  vx_samples: 18           #x方向速度的样本数 (integer, default: 3)
  vtheta_samples: 20       #角速度的样本数 (integer, default: 20)
  sim_granularity: 0.05    #在给定轨迹上的点之间的步长，单位为 meters (double, default: 0.025)
