global_costmap:
  global_frame: /map               #参考系        (string, default: "/map")
  robot_base_frame: base_footprint      #             (string, default: "base_link")

  update_frequency: 5.0            #             (double, default: 5.0)
  publish_frequency: 10.0          #             (double, default: 0.0)
  transform_tolerance: 0.5         #             (double, default: 0.2)

  resolution: 0.05

  static_map: true

  plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
